name: "Run unit tests"

on:
  push:
    branches:
    - "main"

env:
  TEST_PROJECT: "src/Trailblazor.Routing.Tests/Trailblazor.Routing.Tests.csproj"

jobs:
  test:
    name: "Run Trailblazor.Routing unit tests"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 0

    - name: "Setup .NET"
      uses: "actions/setup-dotnet@v4"
      with:
        dotnet-version: 8.0.x

    - name: "Restore dependencies"
      run: "dotnet restore ${{ env.TEST_PROJECT }}"

    - name: "Build project"
      run: "dotnet build ${{ env.TEST_PROJECT }} --no-restore --configuration Release"

    - name: "Run tests"
      run: "dotnet test ${{ env.TEST_PROJECT }} --no-restore --no-build --configuration Release"
